spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9001/
          predicates:
            - Path=/api/users/**
        - id: address/service
          uri: http://localhost:9002/
          predicates:
            - Path=/api/addresses/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
